# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ij9yPVo6-gk1HJSpvKjX17iJ2KI4Q2Gq
"""

from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer
from sumy.summarizers.text_rank import TextRankSummarizer

def summarize_text(text, sentences_count=2):
    # Initialize a parser with the provided text
    parser = PlaintextParser.from_string(text, Tokenizer("english"))

    # Initialize a TextRank summarizer
    summarizer = TextRankSummarizer()

    # Get the summary with the specified number of sentences
    summary = summarizer(parser.document, sentences_count)

    # Convert the summary to a string
    summary_text = " ".join(str(sentence) for sentence in summary)

    return summary_text

if __name__ == "__main__":
    # Prompt the user to input text
    text = input("Enter the text to summarize: ")

    # Prompt the user to specify the number of sentences in the summary
    sentences_count = int(input("Enter the number of sentences in the summary: "))

    # Summarize the text
    summary = summarize_text(text, sentences_count)

    # Print the summary
    print("Summary:")
    print(summary)

!pip install sumy

import nltk
nltk.download("popular")